### ISSUE TITLE
RuntimeWarning: coroutine 'send_to_nr' was never awaited   send_to_nr() v1.0.8

### ISSUE THREAD

**Issue by anikix** [newrelic-experimental/gitlab#25]
Hello, 
 
I'm facing an issue because no data or traces showed up on my New Relic - Service Opentelemetry and a warning message in my pipeline : 

```
RuntimeWarning: coroutine 'send_to_nr' was never awaited 
send_to_nr()
```
![image](https://github.com/newrelic-experimental/gitlab/assets/117655937/e795a031-1eb7-4ac1-bea0-4f91cf6291ae)

For now, i'm just trying to use the New Relic exporter.

I've followed the blog https://newrelic.com/blog/how-to-relic/monitor-gitlab-with-opentelemetry.

Gitlab Runner version : 16.4.2
Using Kubernetes executor with New Relic Exporter 1.0.8:
```
stages:
- new-relic-exporter
new-relic-exporter:
 rules:
   - when: always
 image:
   name: docker.io/dpacheconr/gitlab-exporter:1.0.8
   entrypoint: [""]
 stage: new-relic-exporter
 script:
   - python3 -u /app/main.py
   - echo "Done"
```
Gitlab variables used : 

- GLAB_ENDPOINT
- GLAB_TOKEN : Yes, it's a personnal access token with read_api
- NEW_RELIC_API_KEY: Yes, it's a Licence Ingest API key
- OTEL_EXPORTER_OTEL_ENDPOINT: https://otlp.nr-data.net:4318

Am I missing something ? Thanks

PS : I've tried to test with the 1.0.6 but I got this with no data on New Relic either
![image](https://github.com/newrelic-experimental/gitlab/assets/117655937/3b0265c4-5252-49dd-b62a-35ef52cb8898)

`No data to export, assuming this pipeline jobs are new relic exporters`
